### PR TITLE
IMG-74: implemented new audit format

### PR DESCRIPTION
**Pull request by austeeen**
[IMG-74](https://badgertech.atlassian.net/browse/IMG-74)

I'm considering these changes to be in a working state now.
@jgilbert and @legowave440 have tested this branch. bugs have been fixed as far as they've been found. I've recently fixed the test cases so that they accurately ensure this tool is reporting accurate data in the summaries.
included in this merge is updates to the `README.md` as well with documentation.

---
This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6)

### CODE REVIEW

**Review by jgilbert — CHANGES_REQUESTED** [review]
> Reviewed 18 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6)* status: 18 of 24 files reviewed, 13 unresolved discussions (waiting on @austeeen and @jgilbert)

___
*[ABcompare/README.md, line 52 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MI_fpWQ6tjp9HY4BMEB:-MI_fpWQ6tjp9HY4BMEC:b-gas9ic) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/README.md#L52)):*
> ```
> If the `-i` command is used then intermediate data will be placed in `compare-data/`, this is useful
>  for deeper analysis of the results
> ```

The -i flag is already described above, except for the bit about `compare-data/`
___
*[ABcompare/src/audit_database.py, line 47 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MI_ghKRCT4XM9qY-AIZ:-MI_ghKS9NSAN_Rp3-bf:bwyr56h) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/audit_database.py#L47)):*
> ```Python
>         self.play_path = play_path
>         self.play_name = generic_utils.strip_trailing_slash(self.play_path).split('/')[-1]
>         self._loggr = generic_utils.get_logger(self.__class__.__name__, log_lvl, out_path)
> ```

How did this become `_loggr` instead of `_logger`? Just curious since no other variables are missing vowels. not a big deal, tho.
___
*[ABcompare/src/audit_database.py, line 113 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIdiSco6sFjyMh1-DnM:-MIdiSco6sFjyMh1-DnN:b15wjaz) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/audit_database.py#L113)):*
> ```Python
>         #  "viewport" issue type may be an unnecessary bucket -- could also be useful for counts
> 
>         def drop_in_bucket(bucket, path, name, guid, data):
> ```

This was really confusing until I read further into the source code. The first parameter to `drop_in_bucket` is not itself a bucket, but a list of buckets. In the `for` loop below, `b` is actually a bucket. I would recommend renaming the first parameter `bucket_list`.
___
*[ABcompare/src/audit_database.py, line 123 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIdjCeG9mjt3-P5gZ7b:-MIdjCeG9mjt3-P5gZ7c:blt10la) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/audit_database.py#L123)):*
> ```Python
> 
>             bucket[path].append(Bucket(name))
>             bucket[path][-1].drop(guid, data)
> ```

Even though you can count on the [-1] index to be the one you just added, if there were a point where you introduced threads this may become dangerous. I'd recommend:

```python
    new_bucket = Bucket(name)
    new_bucket.drop(guid, data)
    bucket[path].append(new_bucket)
```
___
*[ABcompare/src/audit_database.py, line 137 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIdmjU-1-9SYPcbA-Z0:-MIdmjU-1-9SYPcbA-Z1:bcasb1k) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/audit_database.py#L137)):*
> ```Python
>             fn = entry[self._false_negative_index]
> 
>             if issue_type == "viewport" and moderation_issue_type == "N/A":
> ```

Since there could be thousands of entries, you may save CPU cycles by checking `issue_type` and `moderation_issue_type` early in the `for` loop before looking up other variables.
___
*[ABcompare/src/audit_database.py, line 150 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MI_qcXo0sfpDr6Kzu4Q:-MI_qcXo0sfpDr6Kzu4R:b5y8oys) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/audit_database.py#L150)):*
> ```
> and moderation_issue_type != "N/A"
> ```
The `continue` above already guarantees that `moderation_issue_type` is not `N/A`.
___
*[ABcompare/src/audit_database.py, line 220 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIdt7ys-lQQmtpv7zDo:-MIdt7ys-lQQmtpv7zDp:b-94k589) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/audit_database.py#L220)):*
> ```Python
> 
>         def classify(fp, fn):
>             if fp == 0:
> ```

I'm a bit surprised that "1" doesn't indicate a False Pos or False Neg in the audit data.
___
*[ABcompare/src/audit_database.py, line 228 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIdouKeCrx6gt0jxsJL:-MIdouKeCrx6gt0jxsJM:b-svd8j) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/audit_database.py#L228)):*
> ```Python
>         found_entry_count = 0
>         entries_found = []
>         for entry in self._summary_data[11:]:
> ```

If `find_entry` is called in a loop, then the complexity is O(n^2). I would recommend creating an auxiliary dictionary of guid -> summary_data indexes to speed this up to O(n).
___
*[ABcompare/src/audit_database.py, line 245 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIdnvmuA5c28xOhQxQu:-MIdnvmuA5c28xOhQxQv:b-fswvmr) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/audit_database.py#L245)):*
> ```Python
>                     found_entry_count = found_entry_count + 1
> 
>         if found_entry_count == 0:
> ```

It looks like `found_entry_count` is simply `len(entries_found)`. You may be able to save yourself a variable if you're interested.
___
*[ABcompare/src/path.py, line 48 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIdpbaY4pY5QEWz4tQu:-MIdpbaY4pY5QEWz4tQv:bp24841) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/path.py#L48)):*
> ```Python
>         self._populate_audit_data_from_buckets()
>         self._relate_scan_event_data_to_audit_data()
>         # self._populate_audit_data()
> ```

has this only been temporarily removed? or has it been replaced by `_populate_audit_data_from_buckets`?
___
*[ABcompare/src/components/writeable.py, line 6 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIe0Mmv7fog1rTOMRT0:-MIe0Mmv7fog1rTOMRT1:b-kn07wi) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/components/writeable.py#L6)):*
> ```Python
> 
> 
> class Writeable:
> ```

It's recommended that all classes derive from `object` to take advantage of type and class system.

```python
class Writeable(object):
...
```
___
*[ABcompare/src/utils/generic_utils.py, line 64 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MI_oeYP42ODa0RRH493:-MI_oeYP42ODa0RRH494:bl12cxt) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/utils/generic_utils.py#L64)):*
> ```Python
>     csvfile.seek(0)
> 
>     return list(map(tuple, csv.reader(csvfile, dialect)))
> ```

the `list()` cast is unnecessary, `map()` returns a list
___
*[ABcompare/tests/test_data/control_play/audit_test_data.csv, line 12 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIe5r4j7PZbEPH2I3g8:-MIe5r4k5cxh9FkTgf8i:bz826v5) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/tests/test_data/control_play/audit_test_data.csv#L12)):*
> ```CSV
> Path,Robot Path Execution Id,Sku,Viewport Guid,Gtin14,Issue Type,Moderation Issue Type,System Issue Count,Moderated Issue Count,Viewport Audit Count,Solution Accepted Count,Solution Rejected Count,Audit Accepted Count,Audit Rejected Count,Fp,Fn,Audit Reason,Moderator
> 1-B-1,,,,,pano_check,N/A,0,0,0,0,1,0,1,0,0,none,
> 1-B-1,3542-91-0,180242,ab24ebc2-a72c-48d2-835e-6cbc3de46a58,36000454956,eOOS,eOOS,1,1,1,1,0,1,0,0,0,,ia.constantino@taskus.com
> ```

The format has changed slightly.
* There are no long runs of commas in the first 9 lines
* Empty strings for "Audit Reason" are ""
* There is now an "Auditor" field after "Moderator
* Moderator and Auditor are N/A if not present.

**Review by jgilbert — CHANGES_REQUESTED** [review]
> Reviewed 6 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6)* status: all files reviewed, 17 unresolved discussions (waiting on @austeeen)

___
*[ABcompare/src/compare_paths.py, line 17 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIe7-ofBTi130YN1HZD:-MIe7-ofBTi130YN1HZE:bh8iyv4) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/compare_paths.py#L17)):*
> ```Python
>     def __init__(self, control_path, compare_path, log_lvl, out_path):
>         self._loggr = generic_utils.get_logger(self.__class__.__name__, log_lvl, out_path)
>         Writeable.__init__(self, self._loggr, data={
> ```

With python "new" classes which inherit from object, this would be:

```python
  super(Compare, self).__init__(...)
```
___
*[ABcompare/src/path.py, line 22 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIe7y429BOE8eHIzGkg:-MIe7y429BOE8eHIzGkh:bbd8s9u) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/path.py#L22)):*
> ```Python
>         self.path_name = os.path.basename(path_path)
> 
>         Writeable.__init__(self, self._loggr)
> ```

recommend making Writeable inherit from object and:

```python
    super(Path, self)__init__(self._loggr)
```
___
*[ABcompare/src/play.py, line 28 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIe9bUB1hv_FBdslk67:-MIe9bUB1hv_FBdslk68:b-gxxiqp) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/play.py#L28)):*
> ```Python
>         self._out_path = out_path
> 
>         Writeable.__init__(self, self._loggr, data={
> ```

Recommend same as elsewhere about inheriting from Writeable. use `super()`
___
*[ABcompare/src/report.py, line 12 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIeFR7fEh7jOa1D8AvO:-MIeFR7fEh7jOa1D8AvP:b9lnou5) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/report.py#L12)):*
> ```Python
> 
> 
> class Report:
> ```

Recommend:
`class Report(object):`

**Review by austeeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6)* status: all files reviewed, 17 unresolved discussions (waiting on @jgilbert)

___
*[ABcompare/README.md, line 52 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MI_fpWQ6tjp9HY4BMEB:-MItehhX3EEGmSKnujKQ:b-896fix) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/README.md#L52)):*
<details><summary><i>Previously, jgilbert (John Gilbert) wrote…</i></summary><blockquote>

> ```
> If the `-i` command is used then intermediate data will be placed in `compare-data/`, this is useful
>  for deeper analysis of the results
> ```

The -i flag is already described above, except for the bit about `compare-data/`
</blockquote></details>

Done.
___
*[ABcompare/src/audit_database.py, line 47 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MI_ghKRCT4XM9qY-AIZ:-MItiPf14OCKOZ1Qnidk:b-uls6g7) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/audit_database.py#L47)):*
<details><summary><i>Previously, jgilbert (John Gilbert) wrote…</i></summary><blockquote>

How did this become `_loggr` instead of `_logger`? Just curious since no other variables are missing vowels. not a big deal, tho.
</blockquote></details>

i believe that's an artifact from old code i used and just went with it. fixed this for clarity.
___
*[ABcompare/src/audit_database.py, line 113 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIdiSco6sFjyMh1-DnM:-MItkZrNCqOBPVT4ptDS:bb7f2mf) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/audit_database.py#L113)):*
<details><summary><i>Previously, jgilbert (John Gilbert) wrote…</i></summary><blockquote>

This was really confusing until I read further into the source code. The first parameter to `drop_in_bucket` is not itself a bucket, but a list of buckets. In the `for` loop below, `b` is actually a bucket. I would recommend renaming the first parameter `bucket_list`.
</blockquote></details>

done
___
*[ABcompare/src/audit_database.py, line 123 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIdjCeG9mjt3-P5gZ7b:-MItkask0hn1hM2_PHjW:bb7f2mf) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/audit_database.py#L123)):*
<details><summary><i>Previously, jgilbert (John Gilbert) wrote…</i></summary><blockquote>

Even though you can count on the [-1] index to be the one you just added, if there were a point where you introduced threads this may become dangerous. I'd recommend:

```python
    new_bucket = Bucket(name)
    new_bucket.drop(guid, data)
    bucket[path].append(new_bucket)
```
</blockquote></details>

done
___
*[ABcompare/src/audit_database.py, line 137 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIdmjU-1-9SYPcbA-Z0:-MItlBov4zFp6V4JVfvk:bb7f2mf) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/audit_database.py#L137)):*
<details><summary><i>Previously, jgilbert (John Gilbert) wrote…</i></summary><blockquote>

Since there could be thousands of entries, you may save CPU cycles by checking `issue_type` and `moderation_issue_type` early in the `for` loop before looking up other variables.
</blockquote></details>

done
___
*[ABcompare/src/audit_database.py, line 150 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MI_qcXo0sfpDr6Kzu4Q:-MItlTpp7cvl-Wn13VJO:bb7f2mf) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/audit_database.py#L150)):*
<details><summary><i>Previously, jgilbert (John Gilbert) wrote…</i></summary><blockquote>

> ```
> and moderation_issue_type != "N/A"
> ```
The `continue` above already guarantees that `moderation_issue_type` is not `N/A`.
</blockquote></details>

done
___
*[ABcompare/src/audit_database.py, line 220 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIdt7ys-lQQmtpv7zDo:-MItmUyX74riwYTwPIne:b-fttp53) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/audit_database.py#L220)):*
<details><summary><i>Previously, jgilbert (John Gilbert) wrote…</i></summary><blockquote>

I'm a bit surprised that "1" doesn't indicate a False Pos or False Neg in the audit data.
</blockquote></details>

it does indicate that -- this is old code i forgot to delete. removed.
___
*[ABcompare/src/audit_database.py, line 228 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIdouKeCrx6gt0jxsJL:-MItmhPf8j1E3TVSseOP:b-tni16o) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/audit_database.py#L228)):*
<details><summary><i>Previously, jgilbert (John Gilbert) wrote…</i></summary><blockquote>

If `find_entry` is called in a loop, then the complexity is O(n^2). I would recommend creating an auxiliary dictionary of guid -> summary_data indexes to speed this up to O(n).
</blockquote></details>

this is dead code, sorry. deleted.
___
*[ABcompare/src/audit_database.py, line 245 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIdnvmuA5c28xOhQxQu:-MItmv_QBMyiIlA7SY5I:b-j0u4b9) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/audit_database.py#L245)):*
<details><summary><i>Previously, jgilbert (John Gilbert) wrote…</i></summary><blockquote>

It looks like `found_entry_count` is simply `len(entries_found)`. You may be able to save yourself a variable if you're interested.
</blockquote></details>

dead code. deleted.
___
*[ABcompare/src/compare_paths.py, line 17 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIe7-ofBTi130YN1HZD:-MItpbrJ-aXyAzPNBU4r:bji7spf) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/compare_paths.py#L17)):*
<details><summary><i>Previously, jgilbert (John Gilbert) wrote…</i></summary><blockquote>

With python "new" classes which inherit from object, this would be:

```python
  super(Compare, self).__init__(...)
```
</blockquote></details>

the `super()` method of initializing isn't necessary and is mostly useful for multiple inheritance. i'm going to prefer `__init__` until it becomes necessary to use super because `__init__` is more explicit and clear.
___
*[ABcompare/src/path.py, line 22 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIe7y429BOE8eHIzGkg:-MItq4TFDUOq_p0NlDEE:b-ntletb) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/path.py#L22)):*
<details><summary><i>Previously, jgilbert (John Gilbert) wrote…</i></summary><blockquote>

recommend making Writeable inherit from object and:

```python
    super(Path, self)__init__(self._loggr)
```
</blockquote></details>

preferring `__init__` until it becomes necessary to use `super()`
___
*[ABcompare/src/path.py, line 48 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIdpbaY4pY5QEWz4tQu:-MItq90u4H7ISMj3bKEe:bgponnu) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/path.py#L48)):*
<details><summary><i>Previously, jgilbert (John Gilbert) wrote…</i></summary><blockquote>

has this only been temporarily removed? or has it been replaced by `_populate_audit_data_from_buckets`?
</blockquote></details>

it was completely replaced. deleted.
___
*[ABcompare/src/play.py, line 28 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIe9bUB1hv_FBdslk67:-MItqPOlB2NtmeLQJOu7:bqq6oo9) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/play.py#L28)):*
<details><summary><i>Previously, jgilbert (John Gilbert) wrote…</i></summary><blockquote>

Recommend same as elsewhere about inheriting from Writeable. use `super()`
</blockquote></details>

preferring `__init__` until it becomes necessary to use `super()`
___
*[ABcompare/src/report.py, line 12 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIeFR7fEh7jOa1D8AvO:-MItqWzf19LRiADPFNJs:bb7f2mf) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/report.py#L12)):*
<details><summary><i>Previously, jgilbert (John Gilbert) wrote…</i></summary><blockquote>

Recommend:
`class Report(object):`
</blockquote></details>

done
___
*[ABcompare/src/components/writeable.py, line 6 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIe0Mmv7fog1rTOMRT0:-MItqp9Z4DHrdftfaLe5:bb7f2mf) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/components/writeable.py#L6)):*
<details><summary><i>Previously, jgilbert (John Gilbert) wrote…</i></summary><blockquote>

It's recommended that all classes derive from `object` to take advantage of type and class system.

```python
class Writeable(object):
...
```
</blockquote></details>

done
___
*[ABcompare/src/utils/generic_utils.py, line 64 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MI_oeYP42ODa0RRH493:-MItra8P2QM5DNM0MVcH:bi1tydq) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/src/utils/generic_utils.py#L64)):*
<details><summary><i>Previously, jgilbert (John Gilbert) wrote…</i></summary><blockquote>

the `list()` cast is unnecessary, `map()` returns a list
</blockquote></details>

correct. it seems this was changed in some python version > 2.7; did not catch the version when looking through the docs on this one.
___
*[ABcompare/tests/test_data/control_play/audit_test_data.csv, line 12 at r1](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6#-MIe5r4j7PZbEPH2I3g8:-MItryYgDVCQNwPb2u-0:bycnzzz) ([raw file](https://github.com/badgertechnologies/imaging_tools/blob/1c663978eb29a552b548516c84368cbf30846dd8/ABcompare/tests/test_data/control_play/audit_test_data.csv#L12)):*
<details><summary><i>Previously, jgilbert (John Gilbert) wrote…</i></summary><blockquote>

The format has changed slightly.
* There are no long runs of commas in the first 9 lines
* Empty strings for "Audit Reason" are ""
* There is now an "Auditor" field after "Moderator
* Moderator and Auditor are N/A if not present.
</blockquote></details>

okay, this is very good to know. i will make this csv reflect those changes. the runs of commas comes from opening the csv in `LibraOffice Calc`on ubuntu. it seems when i save the document it pads each row to have equal spacing. it seems harmless so i won't worry about it for now.

**Review by jgilbert — APPROVED** [review]
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/imaging_tools/6)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
